CREATE TABLE Users
(
    IdU INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FnameU VARCHAR(100) NOT NULL,
    NameU VARCHAR(100) NOT NULL,
    PassU VARCHAR(100) NOT NULL,
    PseudU VARCHAR(100) NOT NULL,
    MailU VARCHAR(100) NOT NULL,
    BirthU DATE NOT NULL,
    DateCreateU DATE NOT NULL
);

CREATE TABLE Games
(
    IdG INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NameG VARCHAR(150) NOT NULL,
    DateG DATE NOT NULL,
    DescG VARCHAR(150) NOT NULL,
    LinkG VARCHAR(150) NOT NULL,
    RateG VARCHAR(150) NOT NULL
);